spring:
  application:
    name: marketplace

  datasource:
    url: jdbc:postgresql://localhost:5456/glowlink_db
    username: glowlink
    password: glowlink123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: glowlinkRedis123

server:
  port: 8080

razorpay:
  api:
    key: ""
    secret: ""

stripe:
  api:
    key: ""